version: "3.8"
services:
# Artifact Complex --- 
  apc_ingestion:
    image: ghcr.io/linus-berg/apc/ingestion:latest
    container_name: apc-ingestion
    env_file:
      - "vars.env"
    depends_on:
      - "apc-ingest-db"
      - "apc-ingest-redis"
      - "apc-rabbitmq"

  apc_api:
    image: ghcr.io/linus-berg/apc/api:latest
    container_name: apc-api
    ports:
      - 9000:80
    env_file:
      - "vars.env"
    depends_on:
      - "apc-ingest-db"
      - "apc-ingest-redis"
      - "apc-rabbitmq"
  
  apm_nuget:
    image: ghcr.io/linus-berg/apc/apm/nuget:latest
    container_name: apm-nuget
    env_file:
      - "vars.env"
    depends_on:
      - "apc-rabbitmq"

  apm_npm:
    image: ghcr.io/linus-berg/apc/apm/npm:latest
    container_name: apm-npm
    env_file:
      - "vars.env"
    depends_on:
      - "apc-rabbitmq"

  acm_http:
    image: ghcr.io/linus-berg/apc/acm/http:latest
    container_name: acm-http
    env_file:
      - "vars.env"
    volumes:
      - "./volumes/output/http/:/data"
    depends_on:
      - "apc-rabbitmq"
