version: "3.8"
services:
# Infrastructure
  apc-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./volumes/mongo_data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  apc-keycloak-db:
    image: postgres:13
    volumes:
      - "./volumes/kc_db:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg123

  apc-keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    restart: always
    depends_on:
     - apc-keycloak-db
    command:
      - start --proxy edge --hostname-strict=false --hostname-url=http://localhost:8090 --db postgres --db-url-host apc-keycloak-db --db-username pg --db-password pg123
    ports:
      - 8090:8080
    volumes:
      - "./volumes/kc_data:/opt/keycloak/data/h2:Z"
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  apc-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@apc-mongo:27017/


  apc-ingest-redis:
    image: redis/redis-stack:latest
    container_name: apc-ingest-redis
    volumes:
      - "./volumes/redis_data:/data"
    ports:
      - 6379:6379
      - 8001:8001

  apc-rabbitmq:
    image: masstransit/rabbitmq
    container_name: apc-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  

# TELEMETRY
  apc-telemetry-grafana:
    image: grafana/grafana-oss:latest
    volumes:
      - "./volumes/grafana_data:/data"
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - 3050:3000
  
  apc-telemetry-tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yaml
      - ./volumes/tempo-data:/tmp/tempo

  apc-telemetry-otel:
    image: otel/opentelemetry-collector:0.78.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel.yml:/etc/otel-collector.yaml
    ports:
      - 4317:4317
      - 4318:4318

  apc-telemetry-prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yml:/etc/prometheus.yaml
