version: "3.8"
services:
# Infrastructure
  apc-mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  apc-mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@apc-mongo:27017/
 
  apc-ingest-redis:
    image: redis/redis-stack:latest
    container_name: apc-ingest-redis
    volumes:
      - "./volumes/redis_data:/data"
    ports:
      - 6379:6379
      - 8001:8001

  apc-rabbitmq:
    image: masstransit/rabbitmq
    container_name: apc-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
